try {
	let x = 3;
} catch (error) {
	let y = 5;
} finally {
	let z = 8;
}

try {
	let y = 9;
} catch (e) {
	let z = 9;
}

try {
	let z = 9;	
} finally {
	let a = 2;
}